### ISSUE TITLE
Update the favicon from storybook to moja-global in storybook setup

### ISSUE THREAD

**Issue by MukulKolpe** [moja-global/ui-library#52]
## Description
As pointed out by @Palaksharma23 during the UI working group meeting, we can work on customizing the [storybook setup](https://moja-global-ui-library.vercel.app/?path=/story/components-accordion--primary). I want to work on updating the favicon from storybook to moja-global.  
@Palaksharma23, @Janvi-Thakkar let me know if this issue is relevant to work on at this point.

**Comment by Palaksharma23** [comment]
Hey @MukulKolpe! Yes, you can start working on this issue :)
