### ISSUE TITLE
Add Introductory page for Storybook Setup of UI Library

### ISSUE THREAD

**Issue by Palaksharma23** [moja-global/ui-library#54]
Currently, we do not have any Introductory page for our Storybook Setup
This page should contain information about Moja Global, a brief description of what the UI library project is, and how to integrate the UI library components in any project using the documentation from Storybook Setup.

**Comment by abhilipsasahoo03** [comment]
I'd like to work on this! @Palaksharma23

**Comment by Palaksharma23** [comment]
Hey! @abhilipsasahoo03, if you need any kind of help or if you face any issues. Please dm me or @Janvi-Thakkar over slack, or you can ask in the #user-interface working group as well :)

**Comment by abhilipsasahoo03** [comment]
Hi @Palaksharma23 I've set up the introductory page with a brief idea about Moja Global and the UI-Library. Where can I find an overview of how to integrate UI library components in other projects just for reference?

**Comment by abhilipsasahoo03** [comment]
Also @Palaksharma23 @Janvi-Thakkar where can I find more details on creating new app with Moja Global UI or maybe adding Moja Global UI to an existing app and Browser Support?
